### ISSUE TITLE
 [vuex] do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by nguyenpr9** [maoberlehner/vuex-map-fields#115]
I 
When i set `strict : true` => Is has problems

But when i set `strict : false` =>  it gone 

see In : https://codesandbox.io/s/vuex-map-fields-nested-properties-forked-gex56?fontsize=14&hidenavigation=1&theme=dark

how can I fix this?

**Comment by geoidesic** [comment]
Can you be a bit more specific about what the problem is?
"It has problems" doesn't tell me anything useful and nor does "it gone".
What is "it" for a start? And what problems?

**Comment by nguyenpr9** [comment]
> Can you be a bit more specific about what the problem is?
> "It has problems" doesn't tell me anything useful and nor does "it gone".
> What is "it" for a start? And what problems?

You can check this in input. when you type, Is has error console

**Comment by geoidesic** [comment]
Ok. This is because your list field is an array. The mutation that `mapFields` is mapping to your list is `updateField`. Your v-model is pointing to a single item in the list, this item is being updated directly, not with a mutator because the mutator is mapped to the list as a whole, not to the individual item of the list. You need to use `mapMultiRowFields` instead of `mapFields` for the list.

See https://github.com/maoberlehner/vuex-map-fields#multi-row-fields

**Comment by nguyenpr9** [comment]
thanks you ! but when i use **mapMultiRowFields** for the list, I can't get items in list to push to other list

please help me check this.
https://codesandbox.io/s/vuex-map-fields-nested-properties-forked-gex56?fontsize=14&hidenavigation=1&theme=dark
