### ISSUE TITLE
items use mapMultiRowFields push [] to other variable

### ISSUE THREAD

**Issue by nguyenpr9** [maoberlehner/vuex-map-fields#116]
when i use **mapMultiRowFields** for the list, I can't get items in list to push to other list

please help me check this.
https://codesandbox.io/s/vuex-map-fields-nested-properties-forked-gex56?fontsize=14&hidenavigation=1&theme=dark

_Originally posted by @nguyenpr9 in https://github.com/maoberlehner/vuex-map-fields/issues/115#issuecomment-688730054_

**Comment by nguyenpr9** [comment]
- [question]

**Comment by geoidesic** [comment]
For a start `mapMultiRowFields` is intended to be used with an iterator, you're not iterating.
Items **are** pushing to the list. When you click the `push Data` button it adds `{ "helo": 10 }` to the array.

**Comment by geoidesic** [comment]
Maybe you should explain what you're actually trying to achieve because without that understanding it's hard to guide you. At the moment you're talking about a list... but there's no list in your code. What you have is a single field, which is not linked to anything but itself and then you have a hard-coded value which you're pushing into an array every time the `push Data` button is clicked.

**Comment by geoidesic** [comment]
It looks to me like maybe what you're trying to achieve is to have a field, which when you enter a value in the field, the value then gets added to an array. However, it's not clear what that has to do with this library. This library isn't designed to deal with that and you don't need this library for that.

What this library is designed for is for mapping a v-model to vuex. That's it. 

Anything more clever than that – like taking an entered value and pushing it into another variable... that's all custom code that has nothing to do with this library.

Maybe you're trying to get the final array that you create to end up in vuex? If so, maybe you should say that, because it's not clear from your code, nor from anything you've said. If that is the case then once again this library isn't designed to cater for that. You should just use a custom mutation.

**Comment by geoidesic** [comment]
The point of this library is to provide some easy ways of not having to write repetitive code for mapping v-models to vuex. It's not however intended to be a Swiss army knife that will replace all kinds of data mappings to vuex. It has quite a limited use-case.

The two use cases are:
1. `mapFields`, which can be used to create a 1-to-1 mapping between a single vuex state node and a v-model and it will provide this as a mapping on the vm instance with getters and setters.
2. `mapMultiRowFields`, which is the same but can be used to create a repeating `v-for` loop on the mapped symbol which can then be used to create a form which corresponds to a single row of data – i.e. e.g. one field per column in a table and the form can create multiple rows within that table via the loop.

That's it. So if you're trying to do something else then this library will not be useful.

**Comment by geoidesic** [comment]
There's an example of how to use `mapMultiRowFields` in the docs: https://codesandbox.io/s/yj1xxx8kn1?file=/src/App.vue

**Comment by nguyenpr9** [comment]
hi @geoidesic,
I have a array object(**items**) and I want to push them to new object (**selectedRows**) but when I push it, The **selectedRows** doesn't have any value in **items**
you can see this : https://codesandbox.io/s/vuex-map-fields-nested-properties-forked-57c2j?fontsize=14&hidenavigation=1&theme=dark

**Comment by geoidesic** [comment]
This library doesn't do that. It's not what this library is for. I suggest you read up on how to use vuex.

**Comment by nguyenpr9** [comment]
but if I use **mapField** i can push them to its. It mean i need to turn off strict to avoid throw an error

**Comment by geoidesic** [comment]
Just because you can do something doesn't mean you should. It's working in that instance by accident, not by design.
The reason you can push to them with strict switched off is because you are misusing vuex. Strict prevents you from misusing vuex.  You're asking for a magic way to prevent you from misusing vuex, which doesn't exist.

As I've explained before. `mapFields` is designed for mapping a single non-multi-row value. `mapMultiRowFields` is designed for handling repeating fields. Neither of them are designed for handling the case where a single field pushes items into an array.

**Comment by geoidesic** [comment]
In your latest example, `mapMultiRowsFields` is of no use. All you're doing is trying to get the first record in the list and push it onto an array. For that use-case `mapFields` will work perfectly, even with strict set to true. As demonstrated here:
https://codesandbox.io/s/vuex-map-fields-nested-properties-forked-i2xnf?file=/src/App.vue

This is why I keep saying – tell us what you're actually trying to build. Then we can guide you. At the moment you're just supplying incorrectly written examples of code that doesn't do anything useful. So all I can tell you is how it's not useful and how it is incorrect.

**Comment by geoidesic** [comment]
It's possible that this library would be of use to you but unless you tell me what it is you're trying to build I won't be able to guide you. I suggest you say something like:

"I'm trying to build a form that can add new values into the `list` array on my vuex store. Each item in the array represents a row of data. The form will have a field for each column, and thus represents a new row."

Is that what you're trying to build? (If so then I don't know why you would have a variable called "selectedRow".)

**Comment by nguyenpr9** [comment]
![Screenshot from 2020-09-08 19-32-05](https://user-images.githubusercontent.com/55862211/92478086-ddebc680-f20b-11ea-8bb1-1efeb8cacad5.png)
 You place tick in the box at the first of each line then the info will be stored in 'selectedRow' variable

**Comment by geoidesic** [comment]
https://codesandbox.io/s/vuex-map-fields-multi-row-fields-forked-28nld?file=/src/App.vue

**Comment by geoidesic** [comment]
However you can do what you're trying to do without `Vuex-map-fields` as shown here: https://codesandbox.io/s/select-rows-from-table-without-vuex-map-fields-ut6xm

The only reason to use this library is to map the v-model of input fields to vuex, which you don't need in order to do what you've shown that you are trying to do.

**Comment by geoidesic** [comment]
So I think you are wasting your time trying to use this library. What you should be trying to do is to learn `vuex`.

**Comment by nguyenpr9** [comment]
thanks you !
