### ISSUE TITLE
Support Vuex 4

### ISSUE THREAD

**Issue by arnauddoub** [maoberlehner/vuex-map-fields#132]
Hello, vuex-map-fields support vuex 4 ?

**Comment by itsChris** [comment]
you have formulated the question in a very general way. I asked myself a similar question and therefore created a test project. if you are interested, you can find it here. 

https://github.com/itsChris/vuex-4-mapfields

As far as I understand, I would claim vue 3 and vuex 4 are supported. for me, this is important because I work with vue 3 and vuex 4. if anyone has experience, I am interested.

**Comment by maoberlehner** [comment]
Thanks @itsChris for answering the question!

`vuex-map-fields` relies on `this.$store.getters` and `this.$store.commit`. If Vuex 4 has the same API for those two, there is no reason why it shouldn't work.

**Comment by darrinmn9** [comment]
If this library does support vue2/3 and vuex3/4, is it worth adding a note of this in the readme?

Also, it seems all of the current unit tests are run on vue2/vuex3, is it possible to have the tests run against vue3/vuex4 as well?
