### ISSUE TITLE
mapMultiRowFields doesn't call the mutation 

### ISSUE THREAD

**Issue by lazycesar** [maoberlehner/vuex-map-fields#98]
Hola!
I pushed an object inside my state
```
addAddressRow(state) {
      state.addresses.push({
        town: {
          zip: ""
        },
        street: ""
      });
    }

```
if I try to change the zip status with dot string notation (address.town.zip) no mutation through updatefield is called

if I change 'address.street', the updatefield mutation is called correctly,

I'll leave you the sample code.
https://codesandbox.io/s/vuex-map-fields-multi-row-fields-l0q02?file=/src/main.js
If you open the console you can see the mutations that activate

Did I do something wrong or is it an anomaly? 

thanks

**Comment by geoidesic** [comment]
Multi-row fields don't work in that way. The field that is mapped is the collection and the default `updateField` method assumes that each repeating property will simply contain a value. So the dot notation in `v-model` should be limited to a single dot.

You should also be getting the following error: 
`Error: [vuex] do not mutate vuex store state outside mutation handlers.`, not sure why that's not happening on your example.

You have two options:
1) Don't do it, it's probably a bad idea.
2) Use a custom `updateFields` method, which you can set up via `createHelpers`. That method should recognise the signature of the unorthodox field and adjust it's output, writing an object to `town` instead of a scalar value. See my example of how to do that here: https://github.com/maoberlehner/vuex-map-fields/issues/103#issuecomment-636690962

**Comment by maoberlehner** [comment]
Thanks @geoidesic for answering!
