### ISSUE TITLE
Can't use a parameter as an array index in mapFields

### ISSUE THREAD

**Issue by Maxiride** [maoberlehner/vuex-map-fields#99]
In a modal to edit a specific client details I am trying to load the infos about that client.

In the Vuex store clients are stored as an array of objects, normally I would load a client details by its index however the syntax shown in the examples to handle arrays works only with an explicitly set value. If I pass a prop or other parametrized value the mapped fields reports "error during evaluation" in the Vue Components computed inspector.

```
example of mapped field
  computed: {
    ...mapFields(['clients[this.id].name'])
  },
```
```
value shown in the Vue inspect tool
name:"(error during evaluation)"
```

Is this a bug or a the package can't actually parse the passed value `this.id`?

**Comment by geoidesic** [comment]
@Maxiride It's not a bug. Firstly your javascript is wrong, it won't parse as javascript, nevermind via this library. What you probably mean is this: 
```
computed: {
    ...mapFields([`clients[${this.id}].name`])
  },
```
However even that won't work because mapFields isn't designed to handle collections, only trees. If you have collections, then see `mapMultiRowFields` example https://codesandbox.io/s/yj1xxx8kn1

**Comment by maoberlehner** [comment]
Thanks @geoidesic for answering!
